baseURL = "https://dseung001.github.io/"
languageCode = "ko-kr"
title = "DevSeung Blog"
theme = "PaperMod"

# 콘텐츠 디렉토리 설정
contentDir = "content"

# URL 구조 설정 - posts 제거
[permalinks]
  posts = "/posts/:year/:month/:day/:contentbasename/"
  tags = "/tags/:slug/"
  categories = "/categories/:slug/"

# 택소노미 설정
[taxonomies]
  category = "categories"
  tag = "tags"

# 메뉴 설정
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

# 파라미터 설정
[params]
  # 기본 정보
  author = "DSeung001"
  description = "개발자 블로그 - AI, 개발, 기술 관련 경험과 인사이트를 공유합니다"
  
  # PaperMod 테마 설정
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # 댓글 시스템 설정
  comments = true
  
  # 색상 테마
  colorScheme = "auto"
  
  # 사이드바 설정
  ShowToc = true
  TocOpen = false
  
  # SEO 최적화 설정
  [params.seo]
    googleAnalytics = "G-FX0PNVWBVG"  # Google Analytics ID 추가 필요
    googleSiteVerification = "KSM9sb3fEefTWY29y1QZ9aTr1GxlxapE8xI-2lKjvZA"  # Google Search Console 인증 코드
    naverSiteVerification = "c15cf65c023f2d9602a5d788b26bf2ff511c407b"
    bingSiteVerification = "your-bing-verification-code"
  
  # 소셜 링크
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dseung001"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:your-email@example.com"

  # Schema.org 설정
  [params.schema]
    publisherType = "Person"
    sameAs = [
      "https://github.com/dseung001"
    ]

  # 이미지 설정
  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"
    theme_color = "#2e2e33"
    msapplication_TileColor = "#2e2e33"

# 빌드 설정
[build]
  writeStats = true
  noChmod = true
  noTimes = true

# 마크다운 설정
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

# 사이트맵 설정
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml" 